version: '3.8'

services:
  banner-masonry:
    image: ghcr.io/jomarjunior/banner-masonry:main-e541d46
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: banner-masonry-app
    environment:
      - NODE_ENV=production
